name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  qa:
    name: 🔹 QA
    uses: oliversalzburg/workflows/.github/workflows/qa-github-action-nodejs.yml@main

  release:
    name: 🔹 Publish
    needs: qa
    permissions:
      contents: write
      id-token: write
      packages: write
      pages: write
      pull-requests: read
    uses: oliversalzburg/workflows/.github/workflows/publish-github-action-nodejs.yml@main
    with:
      is-canary: false
      wants-github-release: true
